export interface MoqRow {
  id: number;
  moq: string;
  individualUnits: string;
  unitsPerInner: string;
  innersPerMaster: string;
  // Per-row overrides (optional — fall back to global when absent)
  pallets?: string;                          // manual pallet count for this MOQ row
  costPerGram?: string;                      // manual cost/gram override for this MOQ row
  fillRateOverrides?: Record<number, string>; // column id → fill rate override
}

export interface Column {
  id: number;
  efficiency: string;
  labor: string;
  unitCost: string;
  level: string;
  type: string;
  units: string;
  tabs: boolean;
  rows: Record<string, string>;
  // When true, the Type field is a free-text name (not a preset selection)
  customType?:     boolean;
  // When set, this column's units + fill rate auto-derive from the source column
  // scaled by (this column's unitsPerInner / source's unitsPerInner)
  sourceId?:       number;
  unitsPerInner?:  string;
  // High-volume fill rate: if units exceed hvThreshold, use hvFillRate instead of base rate
  hvThreshold?:    string;
  hvFillRate?:     string;
  // When set, this column was generated by the Packaging Summary and can be identified
  // for one-way sync updates. Also tracks whether user has manually edited it since last sync.
  summaryId?:      number;
  summaryDirty?:   boolean;
}

export interface ProjectFormData {
  unitWeight: string;
  costPerGram: string;
  // Raw material
  numSkus: string;
  rawMaterialSkus: string;
  leftOverInventoryCost: string;
  leftOverInventoryAbsorb: string;
  // Material intake pallets
  intakeFee: string;
  numPallets: string;
  // Outbound / finished-goods pallets
  outboundFee: string;
  outboundFeeMarkup: string;
  maxPalletWeightLbs: string;    // Max weight per pallet (lbs) — used to auto-calculate finished pallet count
  palletBuffer: string;          // Added pallets buffer on top of auto-calculated pallet count
  manualPallets?: string;        // When set, overrides weight-based auto-calc (used per-MOQ row)
  // Fees
  testingFee: string;
  testingFeeMarkup: string;
  // Setup / QA fee (separate our-cost vs customer price)
  setupFeeOur: string;
  setupFeeCustomer: string;
  ppuDenominator: string;
  // Material markups
  materialOverage: string;
  rawMaterialMarkup: string;
  intakeFeeMarkup: string;
  // Lead time
  leadTimeBufferDays: string;
  startDate: string;
  // Unit weight display unit (g | oz | lb | kg | fl oz)
  unitWeightUnit: string;
}

export interface SummaryRow {
  label: string;
  customerPrice: number;
  ourCosts: number;
}

export interface SummaryTableRow {
  label: string;
  throughput: number | null;      // units / hr (nominal rate × efficiency)
  leadTimeWeeks: number | null;   // productionDays / 5 (no buffer) for components; buffer-adjusted for summary rows
  costPerUnit: number | null;     // customer price per unit = totalPrice / ppuDenominator
  totalWeight: number | null;     // grams
  totalUnits: number | null;
  totalCost: number | null;       // our cost
  totalPrice: number | null;      // customer price
  isLeadTimeSummary?: boolean;    // true for the 3 project-level lead time rows appended after all line items
}

export interface DetailRow {
  label: string;
  projectDetails: number | null;
  projectCosts: number | null;
  isCurrency: boolean;
}

export interface DetailSection {
  title: string;
  overageReq: number | null;
  rows: DetailRow[];
  totalCustomerCost: number;
  totalOurCost: number;
}
